### ISSUE TITLE
Missing Crafting Recipe for Crimson & Warped

### ISSUE THREAD

**Issue by EvoMods** [mgen256/AdditionalLights#23]
Forge 1.20.1
Additional Lights 1.20.1-2.1.7

Missing crafting recipes for anything containing Crimson or Warped logs 
I extracted the .jar and couldn't find the recipes for them in there

**Comment by SkyRunner55** [comment]
still present in recent version, including 1.21.1

**Comment by mgen256** [comment]
I finally fixed it. It was way too late

**Comment by SkyRunner55** [comment]
> I finally fixed it. It was way too late

are you planning to fix it for earlier version as well ? (1.21.1 & 1.21.3)

**Comment by mgen256** [comment]
Due to my current schedule, I have no plans to address older versions. Sorry.

**Comment by SkyRunner55** [comment]
> Due to my current schedule, I have no plans to address older versions. Sorry.

this is fine, thx for anwsering, i'm not gonna die because i can't craft two lamp wood type x)
