### ISSUE TITLE
Illegal Argument Exception - Unable to set facing of block

### ISSUE THREAD

**Issue by AlphaOneBravo** [mgen256/AdditionalLights#4]
[crash-2020-06-26_07.19.23-client.txt](https://github.com/mgen256/AdditionalLights/files/4837127/crash-2020-06-26_07.19.23-client.txt)

Reproduce by simply loading the game, creative in the mossy wall torch and it crashes instant;y.

Once the crash has occurred, restarting the world allows play and the use of that torch but getting a different one or crafting others in survival causes the crash again.

This is does not happen on a forge install with just this mod so it is definitely a mod conflict of some sort.

Hope this helps :)

**Comment by AlphaOneBravo** [comment]
possibly related to this issue so may not be this mod at all.
https://github.com/asiekierka/FoamFix/issues/262

**Comment by mgen256** [comment]
Thanks for reporting!
I fixed the bug and uploaded it to CurseForge.
It will be available for download soon.
please confirm.

**Comment by mgen256** [comment]
https://www.curseforge.com/minecraft/mc-mods/additional-lights/files/2989463

**Comment by AlphaOneBravo** [comment]
Everything seems to work perfectly now :) 

Thank you for your quick response and for making such an amazing and useful mod :)
